/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Templates;

import Entities.KartItem;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author mp
 */
public class KartTemplate extends javax.swing.JPanel implements ListCellRenderer<KartItem> {

    /**
     * Creates new form KartTemplate
     */
    public KartTemplate() {
        setOpaque(true);
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_name_field = new javax.swing.JLabel();
        seller_name_field = new javax.swing.JLabel();
        price_field = new javax.swing.JLabel();

        book_name_field.setText("jLabel1");

        seller_name_field.setText("jLabel2");

        price_field.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(book_name_field)
                .addGap(35, 35, 35)
                .addComponent(seller_name_field)
                .addGap(41, 41, 41)
                .addComponent(price_field)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_name_field)
                    .addComponent(seller_name_field)
                    .addComponent(price_field))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_name_field;
    private javax.swing.JLabel price_field;
    private javax.swing.JLabel seller_name_field;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends KartItem> list,
            KartItem item, int index, boolean isSelected, boolean cellHasFocus) {
       // throw new UnsupportedOperationException("Not supported yet."); 
//To change body of generated methods, choose Tools | Templates.
        book_name_field.setText(item.getBook_name());
        seller_name_field.setText(item.getSeller_name());
        price_field.setText(Double.toString(item.getPrice()));
        
        if(isSelected){
            setBackground(Color.BLUE);
            setForeground(Color.LIGHT_GRAY);
        }else{
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        
        return this;
    }
  
       
}

