
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mp
 */
public class branchPage extends javax.swing.JFrame {

    /**
     * Creates new form branchPage
     */
    String selected,selected_branch,selected_course;
     public static javax.swing.JList<String> subjectList;   
     static String[] branches={"Applied Mechanics","Biotechnology","Chemical Engineering","Civil Engineering","Computer Science and Engineering","Electrical Engineering","Electronics and Communiation Engineering","Mechanical Engineering","Others"};    
     static String[] courses={"BTech","MTech","PhD"};
    public branchPage() {
       
    }
    public branchPage(int selected)
    {
          initComponents();
          DefaultListModel dm= new DefaultListModel(); 
      for(int i=0;i<branches.length;i++)
      dm.addElement(branches[i]);
       
       

      
        jList1.setModel(dm);
        jList1.setSelectedIndex(selected);
//         if(branches[selected]=="Applied Mechanics")
//             jList1.setSelectedIndex(0);
//         else if(branches[selected]=="Biotechnology")
//             jList1.setSelectedIndex(1);
//         else if(branches[selected]=="Chemical Engineering")
//             jList1.setSelectedIndex(2);
//         else if(branches[selected]=="Civil Engineering")
//             jList1.setSelectedIndex(3);
//         else if(branches[selected]=="Coon Engineeringimputer Science and Engineering")
//             jList1.setSelectedIndex(4);
//         else if(branches[selected]=="Electrical Engineering")
//             jList1.setSelectedIndex(5);
//         else if(branches[selected]=="Electronics and Communiation Engineering")
//             jList1.setSelectedIndex(6);
//         else if(branches[selected]=="Mechanical Engineering")
//             jList1.setSelectedIndex(7);
//         else if(branches[selected]=="Others" )
//             jList1.setSelectedIndex(8);
         
          
//         jList2.setLayoutOrientation(JList.HORIZONTAL_WRAP);
         jList2.setVisibleRowCount(1);  
         //for(int i=0;i<selected)
         selected_branch=branches[selected];
         
         DefaultListModel dm2= new DefaultListModel();
         dm2.clear();
        for(int i=0;i<courses.length;i++)
          dm2.addElement(courses[i]);

        jList2.setModel(dm2);
        jList2.setSelectedIndex(0);
         selected_course=courses[0];
        jList2.addListSelectionListener(new ListSelectionListener() {
              @Override
              public void valueChanged(ListSelectionEvent e) {
                  if(!e.getValueIsAdjusting()){
                      selected_branch=jList1.getSelectedValuesList()+"";
                      selected_course=jList2.getSelectedValuesList()+"";
                      String values=jList2.getSelectedValuesList()+" "+jList1.getSelectedValuesList();
                      //values=selected_branch+" "+selected_course;
                      System.out.println(values);
                  }
              }
          });
        jList1.addListSelectionListener(new ListSelectionListener() {
              @Override
              public void valueChanged(ListSelectionEvent e) {
                  if(!e.getValueIsAdjusting()){
                      jList2.setSelectedIndex(0);
                      String values=jList2.getSelectedValuesList()+" "+jList1.getSelectedValuesList();
                      System.out.println(values);
                  }
              }
          });
        
         
    }  
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        toHomePage_button = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setPreferredSize(new java.awt.Dimension(100, 250));
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane2.setViewportView(jList2);

        toHomePage_button.setText("Back to HomePage");
        toHomePage_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHomePage_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(toHomePage_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(toHomePage_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toHomePage_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toHomePage_buttonActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_toHomePage_buttonActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(branchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(branchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(branchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(branchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new branchPage().setVisible(true);
               
                
                
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton toHomePage_button;
    // End of variables declaration//GEN-END:variables

    
}
